{
  lib,
  nixosConfig,
  pkgs,
  ...
}:
let
  cfg = nixosConfig.features;

  # wofi window switcher: rofi's `window` mode replacement (it was part of the
  # old `combi`). Lists view titles and focuses the chosen one by con_id.
  # Covers both Wayland (app_id) and XWayland (window_properties.class) views.
  #
  # NOT using wofi's --pre-display-cmd to hide the id: it substitutes the entry
  # naively ("echo %s | cmd"), which breaks on titles containing |, [], etc.
  # ponytail: title -> con_id is a first-match lookup, so two windows sharing an
  # exact title focus the first; switch to an index-prefixed list if that bites.
  sway-window-switch = pkgs.writeShellScriptBin "sway-window-switch" ''
    set -eu
    swaymsg=${pkgs.sway}/bin/swaymsg
    jq=${pkgs.jq}/bin/jq
    wofi=${pkgs.unstable.wofi}/bin/wofi

    tree="$($swaymsg -t get_tree)"
    sel="$(printf '%s' "$tree" | $jq -r '
      .. | objects
      | select(.type == "con"
          and ((.app_id? // .window_properties.class? // "") != "")
          and ((.name? // "") != ""))
      | .name
    ' | $wofi --dmenu --insensitive --prompt windows)"
    [ -n "$sel" ] || exit 0
    id="$(printf '%s' "$tree" | $jq -r --arg n "$sel" '
      [.. | objects | select(.type == "con" and (.name? // "") == $n) | .id][0] // empty
    ')"
    [ -n "$id" ] && $swaymsg "[con_id=$id] focus"
  '';

  # Pins workspaces to outputs by identity (EDID/model), NOT position — so it's
  # independent of the connector names xe/MST shuffles around. Arrangement
  # (modes + positions) is kanshi's job (see services.kanshi below); this only
  # moves workspaces: ws1 -> middle, ws2 -> laptop (left), ws3 -> right.
  sway-outputs = pkgs.writeShellScriptBin "sway-outputs" ''
    set -euo pipefail
    jq=${pkgs.jq}/bin/jq
    swaymsg=${pkgs.sway}/bin/swaymsg
    json="$($swaymsg -t get_outputs -r)"

    # laptop = the embedded panel (eDP-*); middle = Samsung SMB2440 (sway reports
    # the make as "Samsung Electric Company", so match on the model); right = the
    # remaining external (the anonymous small TV).
    laptop="$($jq -r '[.[] | select(.active) | select(.name | startswith("eDP")) | .name][0] // empty' <<<"$json")"
    exts="$($jq -r '[.[] | select(.active) | select(.name | startswith("eDP") | not) | select(.name != "HEADLESS-1") | {name, model}]' <<<"$json")"
    middle="$($jq -r '[.[] | select(.model == "SMB2440") | .name][0] // empty' <<<"$exts")"
    if [ -n "$middle" ]; then
      right="$($jq -r --arg m "$middle" '[.[] | select(.name != $m) | .name][0] // empty' <<<"$exts")"
    else
      # no Samsung (e.g. work, monitors unknown): fall back to connector order
      middle="$($jq -r '.[0].name // empty' <<<"$exts")"
      right="$($jq -r '.[1].name // empty' <<<"$exts")"
    fi

    # Move workspaces: sway auto-creates one per output in connector order, so
    # `workspace N output X` alone only sets the default and wouldn't relocate
    # them. Restore focus afterwards so a hotplug doesn't jump your view.
    focused="$($jq -r '[.[] | select(.focused) | .name][0] // empty' <<<"$($swaymsg -t get_workspaces -r)")"
    [ -n "$laptop" ] && swaymsg "workspace 2; move workspace to output \"$laptop\"" 2>/dev/null || true
    [ -n "$middle" ] && swaymsg "workspace 1; move workspace to output \"$middle\"" 2>/dev/null || true
    [ -n "$right" ] && swaymsg "workspace 3; move workspace to output \"$right\"" 2>/dev/null || true
    [ -n "$focused" ] && swaymsg "workspace \"$focused\"" 2>/dev/null || true
  '';
in
{
  # applets.nix and swaylock.nix are always imported and each carry their own
  # `lib.mkIf cfg.desktop` guard -- imports themselves can't be conditional,
  # only the config they declare.
  imports = [
    ./applets.nix
    ./swaylock.nix
  ];

  config = lib.mkIf cfg.desktop {
    # Sway session config. Generated by config.nix (not a plain file) so that
    # every command a binding launches resolves to a real store path.
    xdg.configFile."sway/config".text = import ./config.nix { inherit pkgs; };

    # Bind every Wayland user service (kanshi, swayidle, …) to sway-session.target
    # instead of graphical-session.target. Home Manager's default target is
    # started by NixOS *before* sway (the non-systemd-aware session wrapper starts
    # nixos-fake-graphical-session.target), so a condition on WAYLAND_DISPLAY is
    # evaluated with no compositor around and the service is skipped for the whole
    # session. The sway config starts sway-session.target right after importing
    # the env (it includes /etc/sway/config.d/nixos.conf).
    wayland.systemd.target = "sway-session.target";

    # Output arrangement via EDID-matched profiles (the Wayland autorandr). kanshi
    # applies the profile whose outputs are all present, on every hotplug — so the
    # xe/MST connector-name churn no longer matters.
    services.kanshi = {
      enable = true;
      settings = [
        {
          profile = {
            name = "home";
            outputs = [
              {
                criteria = "LG Display 0x078B Unknown";
                mode = "1920x1200@120Hz";
                position = "0,0";
              }
              {
                criteria = "Samsung Electric Company SMB2440 H9XZ806373";
                mode = "1920x1080@60Hz";
                position = "1920,0";
              }
              {
                criteria = "Avolites Ltd HDTV Unknown";
                mode = "1360x768@60Hz";
                position = "3840,0";
              }
            ];
          };
        }
        {
          profile = {
            name = "mobile";
            outputs = [
              {
                criteria = "LG Display 0x078B Unknown";
                mode = "1920x1200@120Hz";
                position = "0,0";
              }
            ];
          };
        }
      ];
    };

    home.packages = [
      # The bar itself is not here -- waybar comes from programs.waybar in
      # home-manager/modules/waybar/, together with its systemd user unit. Only
      # the tray/manager applets live below.
      pkgs.blueman
      # Wayland output-arrangement GUI (arandr is X11-only — no xrandr under sway).
      pkgs.wdisplays
      # grim/slurp do the plain region grab; satty (native Wayland, unlike
      # flameshot which needed QT_QPA_PLATFORM=xcb and left its clipboard
      # writes stuck on the XWayland side -- see the $mod+Print keybind in
      # config.nix) does the annotate/editor part, piping straight to wl-copy.
      pkgs.grim
      pkgs.slurp
      pkgs.satty
      pkgs.wl-clipboard
      sway-outputs
      sway-window-switch
      (pkgs.writeShellScriptBin "sway-autostart" ''
        set -u
        # nm-applet, syncthingtray, blueman (on-demand via $mod+b), dunst, waybar
        # and swaync are all systemd user services or keybinds now -- nothing
        # left here to background/pkill. Just the workspace pinning.

        # pin workspaces once, then re-pin on every monitor hotplug (kanshi
        # meanwhile owns the actual output arrangement)
        sway-outputs
        (${pkgs.sway}/bin/swaymsg -t subscribe '["output"]' | while read -r _; do sway-outputs; done) &
      '')
    ];

    # wofi/waybar/swaync configs are shared via home-manager/modules/{wofi,waybar,swaync}.
  };
}
